"""Write the course data files into src/engstoch/data (seed 2026). Run: python tools/make_course_data.py

1. call_centre.csv   - 20 weekdays of calls (arrival time, handle time) from a non-homogeneous Poisson process with
                       the profile models.call_centre_rate, 15 % more calls on Mondays, lognormal handle times
                       (mean 4 min, cv 0.8); faults: a telephony outage on day 8 from 13:00 to 14:30 (no calls
                       logged) and 0.4 % of handle times logged as 0 (dropped connections).
2. weather.csv       - ten years of daily dry (0) / wet (1) indicators from a two-state chain whose transition
                       probabilities vary with the season (a homogeneous chain is the wrong model, mildly).
3. machine_log.csv   - two years of a machine's state changes (up / degraded / down) from models.machine(); the
                       log ends while the machine is up (the last sojourn is censored).
4. prices.csv        - 1500 trading days of a stock following geometric Brownian motion, annual drift 8 %,
                       volatility 18 % for 1000 days and 35 % afterwards (a regime change).
"""

import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from engstoch import models  # noqa: E402

OUT = Path(__file__).resolve().parents[1] / "src" / "engstoch" / "data"
OUT.mkdir(parents=True, exist_ok=True)
rng = np.random.default_rng(2026)

# 1. call centre ---------------------------------------------------------------------------------------------
cc = models.CALL_CENTRE
rows = []
for day in range(1, 21):
    weekday = (day - 1) % 5  # day 1 is a Monday
    factor = cc["monday_factor"] if weekday == 0 else 1.0
    lam_max = cc["rate_max"] * factor
    t = cc["open"]
    while True:
        t += rng.exponential(1.0 / lam_max)
        if t >= cc["close"]:
            break
        if rng.random() < factor * models.call_centre_rate(t) / lam_max:
            if day == 8 and 13.0 <= t < 14.5:
                continue  # outage: the call never reached the logger
            mu, s = cc["service_lognormal"]
            handle = float(np.exp(mu + s * rng.standard_normal()))
            if rng.random() < 0.004:
                handle = 0.0
            rows.append((day, ["Mon", "Tue", "Wed", "Thu", "Fri"][weekday], t, handle))
lines = [
    "# Calls offered to a service line over 20 weekdays (day 1 = Monday), 08:00-20:00.",
    "# arrival_h: arrival time in hours since midnight; handle_min: talk + wrap-up time in minutes.",
    "# Known issues: a telephony outage on day 8 (13:00-14:30, no calls logged); a few handle times of 0 are dropped connections.",
    "# Generated by tools/make_course_data.py from engstoch.models.call_centre_rate (seed 2026). Columns: day, weekday, arrival_h, handle_min.",
    "day,weekday,arrival_h,handle_min",
]
lines += [f"{d},{w},{a:.5f},{h:.3f}" for d, w, a, h in rows]
(OUT / "call_centre.csv").write_text("\n".join(lines) + "\n")

# 2. weather -------------------------------------------------------------------------------------------------
n_days = 3650
doy = np.arange(n_days) % 365
p_dw = 0.20 + 0.10 * np.cos(2 * np.pi * (doy - 15) / 365)  # wetter winters
p_wd = 0.55 - 0.15 * np.cos(2 * np.pi * (doy - 15) / 365)
x = np.zeros(n_days, dtype=int)
for k in range(1, n_days):
    x[k] = (rng.random() < p_dw[k]) if x[k - 1] == 0 else (rng.random() >= p_wd[k])
lines = [
    "# Daily rain indicator at a station over ten years of 365 days (1 = wet day, at least 1 mm).",
    "# Generated by tools/make_course_data.py from a two-state chain with seasonal transition probabilities (seed 2026). Columns: day, day_of_year, wet.",
    "day,day_of_year,wet",
]
lines += [f"{k},{doy[k] + 1},{x[k]}" for k in range(n_days)]
(OUT / "weather.csv").write_text("\n".join(lines) + "\n")

# 3. machine log ---------------------------------------------------------------------------------------------
m = models.machine()
path = m["chain"].simulate(2 * 8760.0, "up", rng)
while m["chain"].states[path["states"][-1]] != "up":  # end the log in the up state: drop the trailing events
    path["times"], path["states"] = path["times"][:-1], path["states"][:-1]
lines = [
    "# State changes of a production machine over two years (17520 h); the log starts up at t = 0 and ends at 17520 h.",
    "# The final sojourn (from the last event to 17520 h) is incomplete: the machine was still up when the log was exported.",
    "# Generated by tools/make_course_data.py from engstoch.models.machine() (seed 2026). Columns: time_h, state.",
    "time_h,state",
]
lines += [f"{t:.4f},{m['chain'].states[s]}" for t, s in zip(path["times"], path["states"])]
(OUT / "machine_log.csv").write_text("\n".join(lines) + "\n")

# 4. prices --------------------------------------------------------------------------------------------------
n = 1500
dt = 1 / 252
sig = np.where(np.arange(n) < 1000, 0.18, 0.35)
r = (0.08 - 0.5 * sig**2) * dt + sig * np.sqrt(dt) * rng.standard_normal(n)
S = 100 * np.exp(np.r_[0.0, np.cumsum(r)])
lines = [
    "# Daily closing prices of a stock over 1501 trading days (252 per year).",
    "# Generated by tools/make_course_data.py from geometric Brownian motion with drift 8 %/yr; the volatility changes during the record (seed 2026). Columns: day, close.",
    "day,close",
]
lines += [f"{k},{v:.4f}" for k, v in enumerate(S)]
(OUT / "prices.csv").write_text("\n".join(lines) + "\n")

for f in sorted(OUT.glob("*.csv")):
    print(f"{f.name:<20} {sum(1 for _ in f.open()) - 1:6d} lines  {f.stat().st_size / 1024:7.1f} kB")
